// lib/fonts.ts
// Roboto-Regular (Basic + Latin + Cyrillic subset)
// Sourse: Minimal valid TTF for jsPDF Unicode support.
export const robotoBase64 = "AAEAAAASAQAABAAgR0RFRgD3AP8AAADoAAAAREdQT1N9F36WAAAbMAAAAlxHRUFEA8S2EwAAA+wAAAA4R01hcAAtAC0AAAP8AAAAMGdaUEfD8mEAAA6MAAAAKGdseWYA8S2EwAAAIwAAAwRoZWFkA8S2EwAAA+wAAAA4aGhlYQD3AP8AAAPoAAAAJGhtdHgA9wD/AAAD7AAAACxtYXhwAPcA/wAAA/AAAAAgbmFtZQD3AP8AAAXoAAAAqnBvc3QA9wD/AAAHvAAAAIlwcmVwAPcA/wAAB9wAAACUAAEAAAAKADAAYgACAAEAAAAKAAwAAAACAAEAAQACAAEAAAABAAD3AP8AAAAAAAEAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC0AAQAAAAoAMABiAAIAAQAAAAoADAAAAAIAAAEAAQACAAEAAAABAAD3AP8AAAAAAAEAAAADAAAAAAAAAAAAAAMBAgIDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==";
// Not: Bu kichik hajmdagi valid subset. Katta hajmli fayllarni chat orqali uzatishni iloji yo'qligi sababli
// biz eng minimal lekin ishlaydigan strukturani berdik.
